### ISSUE TITLE
C2->C3 upgrade error: Undefined index

### ISSUE THREAD

**Issue by michaelroper** [fruitstudios/craft-linkit#30]
Hey guys,

Just upgrading a site from Craft v2 to v3, and I can't seem to install your plugin after doing a `composer require` (latest v1.0.8, cleared cache, etc). It seems to failing on the data migration step... 

When I look in the web.log file, I can see the following exception...
```
2018-05-23 14:24:43 [127.0.0.1][46][-][error][craft\db\MigrationManager::migrateUp] Failed to apply Install (time: 0.002s). Output:
    > delete from {{%plugins}} ... done (time: 0.000s)
Exception: Undefined index: types (/Users/michael/Sites/v-web/vendor/fruitstudios/linkit/src/migrations/Install.php:80)
#0 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/web/ErrorHandler.php(84): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/michael....', 80)
#1 /Users/michael/Sites/v-web/vendor/fruitstudios/linkit/src/migrations/Install.php(80): craft\web\ErrorHandler->handleError(8, 'Undefined index...', '/Users/michael....', 80, Array)
#2 /Users/michael/Sites/v-web/vendor/fruitstudios/linkit/src/migrations/Install.php(54): fruitstudios\linkit\migrations\Install->_migrateFieldSettings(Array)
#3 /Users/michael/Sites/v-web/vendor/fruitstudios/linkit/src/migrations/Install.php(22): fruitstudios\linkit\migrations\Install->_upgradeFromCraft2()
#4 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/db/Migration.php(56): fruitstudios\linkit\migrations\Install->safeUp()
#5 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/base/Plugin.php(122): craft\db\MigrationManager->migrateUp(Object(fruitstudios\linkit\migrations\Install))
#7 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/services/Plugins.php(472): craft\base\Plugin->install()
#8 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/controllers/PluginsController.php(48): craft\services\Plugins->installPlugin('linkit')
#9 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#10 /Users/michael/Sites/v-web/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/michael/Sites/v-web/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('install-plugin', Array)
#13 /Users/michael/Sites/v-web/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#14 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('plugins/install...', Array)
#15 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('plugins/install...', Array)
#16 /Users/michael/Sites/v-web/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /Users/michael/Sites/v-web/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/michael/Sites/v-web/web/index.php(21): yii\base\Application->run()
#19 /Users/michael/.composer/vendor/laravel/valet/server.php(147): require('/Users/michael....')
#20 {main}

2018-05-23 14:24:43 [127.0.0.1][46][-][trace][yii\db\Transaction::rollBack] Roll back transaction
```

Any ideas on how to work around this?

**Comment by michaelroper** [comment]
Hey @samhibberd! Did you happen to see this issue, and have any idea of what might cause it, or how I might work around it? Cheers..

**Comment by samhibberd** [comment]
Hey @michaelroper, the migration is failing to find any link types set in the settings for the v2 fields, which shouldn't ever be the case. I have added a check to ensure that the key exists so it doesn't get stuck. 

If it's cool, it would be useful to get a look at the field settings table from the v2 database just to check i'm not missing anything.

Release with the fix will be out today.

**Comment by michaelroper** [comment]
Hey @samhibberd - I fixed that field without settings that you mentioned (prior to updating the plugin), and that fixed the issue. Cheers for your help!
