### ISSUE TITLE
LinkIt field returning Javascript Errors when trying to select entry as link in CP

### ISSUE THREAD

**Issue by brianrivet-tilt** [fruitstudios/craft-linkit#95]
Hi,

I'm running LinkIt 1.1.12.1 on Craft 3.7.30.1. I'm seeing an issue on one of my sites where I set the link to point to an entry, and when the modal appears to allow me to select the target entry, it never renders the list, it just sites there with the spinner. When I check the javascript console in the browser I see the following errors come up when I trigger the modal:

Garnish.js:323 Uncaught TypeError: t.addClass is not a function
    at Object.ariaHide (Garnish.js:323:23)
    at SVGSVGElement.<anonymous> (Garnish.js:272:25)
    at Function.each (jquery.js?v=1642821788:2:3002)
    at w.fn.init.each (jquery.js?v=1642821788:2:1482)
    at Object.hideModalBackgroundLayers (Garnish.js:267:33)
    at s.constructor.show (Modal.js:136:17)
    at s.constructor.show (BaseElementSelectorModal.js:149:14)
    at s.constructor.e [as show] (Base.js:69:31)
    at s.constructor.init (Modal.js:49:26)
    at s.constructor.init (BaseElementSelectorModal.js:35:14)
ariaHide @ Garnish.js:323
(anonymous) @ Garnish.js:272
each @ jquery.js?v=1642821788:2
each @ jquery.js?v=1642821788:2
hideModalBackgroundLayers @ Garnish.js:267
show @ Modal.js:136
show @ BaseElementSelectorModal.js:149
e @ Base.js:69
init @ Modal.js:49
init @ BaseElementSelectorModal.js:35
e @ Base.js:69
constructor @ Base.js:21
s.constructor @ Base.js:30
s.constructor @ Base.js:30
s.constructor @ Base.js:30
createElementSelectorModal @ Craft.js:1657
createModal @ BaseElementSelectInput.js:331
showModal @ BaseElementSelectInput.js:324
(anonymous) @ Base.js:146
o @ jquery.js?v=1642821788:2
dispatch @ jquery.js?v=1642821788:2
v.handle @ jquery.js?v=1642821788:2
trigger @ jquery.js?v=1642821788:2
(anonymous) @ jquery.js?v=1642821788:2
each @ jquery.js?v=1642821788:2
each @ jquery.js?v=1642821788:2
trigger @ jquery.js?v=1642821788:2
click.garnish-activate @ Garnish.js:810
dispatch @ jquery.js?v=1642821788:2
v.handle @ jquery.js?v=1642821788:2
BaseElementSelectorModal.js:186 

Uncaught TypeError: Cannot read properties of null (reading 'html')
    at Object.success (BaseElementSelectorModal.js:186:28)
    at u (jquery.js?v=1642821788:2:28643)
    at Object.fireWith [as resolveWith] (jquery.js?v=1642821788:2:29391)
    at S (jquery.js?v=1642821788:2:80331)
    at XMLHttpRequest.<anonymous> (jquery.js?v=1642821788:2:82799)

Can you help me to resolve?

**Comment by brianrivet-tilt** [comment]
Just for more info, the field is being used inside of a Neo Block. The issue isn't happening on all the entries, etc. it seems to be limited to a single entry, the home page.
